apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmsingle-victoria-metrics-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: victoria-metrics-server
      app.kubernetes.io/name: vmsingle
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: victoria-metrics-server
        app.kubernetes.io/name: vmsingle
    spec:
      containers:
      - args:
        - -httpListenAddr=:8429
        - -retentionPeriod=1d
        - -storageDataPath=/victoria-metrics-data
        image: victoriametrics/victoria-metrics:v1.93.4
        name: vmsingle
        ports:
        - containerPort: 8429
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /victoria-metrics-data
          name: data
      serviceAccountName: vmsingle-victoria-metrics-server
      volumes:
      - name: data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: victoria-metrics-server
    app.kubernetes.io/name: vmsingle
  name: vmsingle-victoria-metrics-server
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8429
    protocol: TCP
    targetPort: 8429
  selector:
    app.kubernetes.io/instance: victoria-metrics-server
    app.kubernetes.io/name: vmsingle
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: victoria-metrics-server
    app.kubernetes.io/name: vmsingle
  name: vmsingle-victoria-metrics-server
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmsingle-victoria-metrics-server
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmsingle-victoria-metrics-server
subjects:
  - kind: ServiceAccount
    name: vmsingle-victoria-metrics-server
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: vmsingle-victoria-metrics-server
  apiGroup: rbac.authorization.k8s.io
