apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zonekeeper
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zonekeeper
  template:
    metadata:
      labels:
        app: zonekeeper
    spec:
      serviceAccountName: zonekeeper
      containers:
      - name: zonekeeper
        image: tanmaybhat/zonekeeper:1.3.0
        ports:
        - containerPort: 8081
        args:
        - "--pod-label-selector=app=metrics-exporter"
        env:
        - name: WATCH_NAMESPACE
          value: "default,monitoring"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zonekeeper
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zonekeeper
subjects:
  - kind: ServiceAccount
    name: zonekeeper
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: zonekeeper
  apiGroup: rbac.authorization.k8s.io

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: zonekeeper
  namespace: monitoring
